INSERT INTO BOOK_CATALOG (BOOK_ID, BOOK_NAME, STOCK, PRICE)
VALUES ('CATALOG-001', '도메인 주도 설계 첫걸음',100,22500);
INSERT INTO BOOK_CATALOG (BOOK_ID, BOOK_NAME, STOCK, PRICE)
VALUES ('CATALOG-002', '도메인 주도 개발 시작하기: DDD 핵심 개념 정리부터 구현까지',100,25200);
INSERT INTO BOOK_CATALOG (BOOK_ID, BOOK_NAME, STOCK, PRICE)
VALUES ('CATALOG-003', '오브젝트',100,34200);
INSERT INTO BOOK_CATALOG (BOOK_ID, BOOK_NAME, STOCK, PRICE)
VALUES ('CATALOG-004', '면접을 위한 CS 전공지식 노트',100,21600);
INSERT INTO BOOK_CATALOG (BOOK_ID, BOOK_NAME, STOCK, PRICE)
VALUES ('CATALOG-005', '객체지향의 사실과 오해',100,18000);
