name: Pull Request Test

#pull request 생성/동기화/재생성 될 때 스크립트 실행
on:
  pull_request:
    type: [opened, synchronize, reopened]

# 모든 조회 권한 허용
permissions: read-all

jobs:
  build-test:
    runs-on: ubuntu-latest  #우분투 최신버전으로 실행
    permissions:
      contents: read
      pull-request: write
    step:
      - name: Git Checkout
        uses: actions/checkout@v3.0.2
