name: Pull Request Test

#pull request 생성/동기화/재생성 될 때 스크립트 실행
on:
  pull_request:
    types: [opened, synchronize, reopened]

# 모든 조회 권한 허용
permissions: read-all

jobs:
  build-test:
    runs-on: ubuntu-latest  #우분투 최신버전으로 실행
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3.0.2

      - name: JDK 설치
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu  #zule에서 java17 버전 사용
          cache: 'gradle'

      - name: Gradle Build
        run: |  #병렬로 동작
          ./gradlew build --parallel

      - name: Coverage Report
        uses: madrapps/jacoco-report@v1.6.1
        with:
          token: ${{ secretes.GITHUB_TOKEN }}
          title: Code Coverage Report
          update-comment: true
          min-coverage-overall: 10
          min-coverage-changed-files: 10
          # github pr 에 jacoco 코멘트를 남겨줌
          paths: |
            ${{ github.workspace }}/**/build/jacoco/jacoco.xml
