ALTER TABLE student_score MODIFY id BIGINT NOT NULL COMMENT '학생점수 고유키';
ALTER TABLE passed_exam MODIFY id BIGINT NOT NULL COMMENT '시험 합격 고유키';
ALTER TABLE failed_exam MODIFY id BIGINT NOT NULL COMMENT '시험 불합격 고유키';