server:
  port: 0

spring:
  application:
    name: user-service
  rabbitmq:
    host: localhost
    port: 5672
    stream:
      username: adminyj
      password: test12!@
  jpa:
    database: mysql
    hibernate.ddl-auto: update
    format_sql: true
    show-sql: true

eureka:
  instance:
              ## spring.cloud.client.hostname 사용 시 io address가 들어옴
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

greeting:
  message: Welcome to user-info E-commerce

jasypt:
  encryptor:
    bean: jasyptEncryptor

logging:
  level:
    com.example.userservice.client: DEBUG

management:
  endpoints:
    web:
      exposure:
        ## refresh: Spring config에 있는 설정정보를 갱신
        include: refresh, health, beans, busrefresh
