server:
  port: 0

spring:
  application:
    name: user-service
  rabbitmq:
    host: localhost
    port: 5672
    stream:
      username: adminyj
      password: test12!@
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(uEbqEYsvcO6g+Nv/pR91tggoYY5R0swYVHbMYWxUxUiUBmHRB/t3YtYdhye7G6a4jdu+zXnXSYCITNauVI7Dq7SRGuR2SXpaZTpJ2QzLaaX9i8fjyeQvYsMwuZZpbPREOJUC4ruNVPMcBTQBwZ7nNZMw5/ABdkzm2Z3Y4QThTeE=)
    username: ENC(BHmzH6N1SF+8i28j1sGPGr/5CLXsirLLLobj6Y0EeabsvuBZ9PUntRr4A/MNwHce)
    password: ENC(amiQL2z0fbPr5ivcMingFGTFPPbEcvVWbwR4yA5ZV8/mCxWB/uZW/yrB21NSmOxY)
  jpa:
    database: mysql
    hibernate.ddl-auto: update
    format_sql: true
    show-sql: true

eureka:
  instance:
              ## spring.cloud.client.hostname 사용 시 io address가 들어옴
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

greeting:
  message: Welcome to user-info E-commerce

jasypt:
  encryptor:
    password: ${jasypt-key}
    bean: jasyptEncryptor

logging:
  level:
    root: debug

management:
  endpoints:
    web:
      exposure:
        ## refresh: Spring config에 있는 설정정보를 갱신
        include: refresh, health, beans, busrefresh
