#!/bin/sh

targetFiles=$(git diff --staged --name-only)

echo "Apply Spotless..."
cd exam-service
./gradlew spotlessApply

for file in $targetFiles; do
  if test -f "$file"; then
    git add $file
  fi
done
