server:
  port: 8081
#  port: ${random.int(10000,51000)
spring:
  application:
    name: my-first-service

  jpa:
    hibernate:
      ddl-auto: update
    format_sql: true
    show-sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://0.0.0.0:3307/bookmark
    username: root
    password: Daily12!@

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#      defaultZone: http://localhost:8762/eureka, http://kubernetes.docker.internal:8763/eureka
#  instance:
#    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${random.value}}
#    prefer-ip-address: true
