server:
  port: 0

spring:
  application:
    name: order-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(uEbqEYsvcO6g+Nv/pR91tggoYY5R0swYVHbMYWxUxUiUBmHRB/t3YtYdhye7G6a4jdu+zXnXSYCITNauVI7Dq7SRGuR2SXpaZTpJ2QzLaaX9i8fjyeQvYsMwuZZpbPREOJUC4ruNVPMcBTQBwZ7nNZMw5/ABdkzm2Z3Y4QThTeE=)
    username: ENC(BHmzH6N1SF+8i28j1sGPGr/5CLXsirLLLobj6Y0EeabsvuBZ9PUntRr4A/MNwHce)
    password: ENC(amiQL2z0fbPr5ivcMingFGTFPPbEcvVWbwR4yA5ZV8/mCxWB/uZW/yrB21NSmOxY)
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        auto_quote_keyword: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

logging:
  level:
    com.example.orderservice: DEBUG
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

jasypt:
  encryptor:
    password: ${jasypt-key}
    bean: jasyptEncryptor

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh, info, metrics, prometheus
    prometheus:
      enabled: true
    metrics:
      enabled: true
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: B3
      produce: B3_MULTI
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
