server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: localhost
    port: 5672
    stream:
      username: adminyj
      password: test12!@
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yeahdy/bookmark-config.git

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
